apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myfastapi
  template:
    metadata:
      labels:
        app: myfastapi
    spec:
      containers:
      - name: myfastapi
        image: myfastapi:1.0
        imagePullPolicy: Never     # ← 반드시 Never로 (풀 시도 금지)
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: myfastapi-service
spec:
  type: NodePort
  selector:
    app: myfastapi
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30080