kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: dev
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      - containerPort: 30080         # ← 추가
        hostPort: 30080              # ← 추가
        protocol: TCP
  - role: worker
  - role: worker

